[package]
name = "libsobox-sys"
version = "0.1.0"
edition = "2021"

[build-dependencies]
# We can technically use any non-EF bindgen version here, but importing the
# global workspace one is more convenient.
bindgen.workspace = true
